數值


In [201]:
from keras.models import Sequential

from keras.layers import Dense

from sklearn.datasets import make_regression

from sklearn.preprocessing import MinMaxScaler

import keras

In [202]:
import pandas as pd
datasets = pd.read_csv('abalone.data.csv',encoding='unicode_escape')

In [203]:
print (datasets)

     M  0.455  0.365  0.095   0.514  0.2245   0.101    0.15  15
0       M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7
1       F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9
2       M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10
3       I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7
4       I  0.425  0.300  0.095  0.3515  0.1410  0.0775  0.1200   8
...   ...    ...    ...    ...     ...     ...     ...     ...  ..
4171    F  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11
4172    M  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10
4173    M  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9
4174    F  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10
4175    M  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12

[4176 rows x 9 columns]


In [204]:
datasets.columns=['Sex',
              'Length',
              'Diameter',
              'Height',
              'Whole weight',
              'Shucked weight',
              'Viscera weight',
              'Shell weight',
              'Rings'
              ]

In [205]:
print (datasets)

     Sex  Length  Diameter  ...  Viscera weight  Shell weight  Rings
0      M   0.350     0.265  ...          0.0485        0.0700      7
1      F   0.530     0.420  ...          0.1415        0.2100      9
2      M   0.440     0.365  ...          0.1140        0.1550     10
3      I   0.330     0.255  ...          0.0395        0.0550      7
4      I   0.425     0.300  ...          0.0775        0.1200      8
...   ..     ...       ...  ...             ...           ...    ...
4171   F   0.565     0.450  ...          0.2390        0.2490     11
4172   M   0.590     0.440  ...          0.2145        0.2605     10
4173   M   0.600     0.475  ...          0.2875        0.3080      9
4174   F   0.625     0.485  ...          0.2610        0.2960     10
4175   M   0.710     0.555  ...          0.3765        0.4950     12

[4176 rows x 9 columns]


In [207]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
datasets['Sex'] = labelencoder.fit_transform(datasets['Sex'])

In [9]:
#from sklearn import preprocessing
#建立RobustScaler物件
#robust = preprocessing.RobustScaler()
# 資料標準化
#data_rob = robust.fit_transform(datasets)

In [208]:
sex=datasets[['Sex']]
sex

Sex
0       2
1       0
2       2
3       1
4       1
...   ...
4171    0
4172    2
4173    2
4174    0
4175    2

[4176 rows x 1 columns]

In [209]:
print (datasets)

      Sex  Length  Diameter  ...  Viscera weight  Shell weight  Rings
0       2   0.350     0.265  ...          0.0485        0.0700      7
1       0   0.530     0.420  ...          0.1415        0.2100      9
2       2   0.440     0.365  ...          0.1140        0.1550     10
3       1   0.330     0.255  ...          0.0395        0.0550      7
4       1   0.425     0.300  ...          0.0775        0.1200      8
...   ...     ...       ...  ...             ...           ...    ...
4171    0   0.565     0.450  ...          0.2390        0.2490     11
4172    2   0.590     0.440  ...          0.2145        0.2605     10
4173    2   0.600     0.475  ...          0.2875        0.3080      9
4174    0   0.625     0.485  ...          0.2610        0.2960     10
4175    2   0.710     0.555  ...          0.3765        0.4950     12

[4176 rows x 9 columns]


In [210]:
datasets.drop_duplicates()
(datasets.astype(str) == ' ?').any(1)
datasets = datasets[~(datasets.astype(str) == ' ?').any(1)]
lack = datasets.isnull()

In [211]:
x=datasets[["Sex","Length","Diameter","Height","Whole weight","Shucked weight","Viscera weight","Shell weight"]]
x

Sex  Length  Diameter  ...  Shucked weight  Viscera weight  Shell weight
0       2   0.350     0.265  ...          0.0995          0.0485        0.0700
1       0   0.530     0.420  ...          0.2565          0.1415        0.2100
2       2   0.440     0.365  ...          0.2155          0.1140        0.1550
3       1   0.330     0.255  ...          0.0895          0.0395        0.0550
4       1   0.425     0.300  ...          0.1410          0.0775        0.1200
...   ...     ...       ...  ...             ...             ...           ...
4171    0   0.565     0.450  ...          0.3700          0.2390        0.2490
4172    2   0.590     0.440  ...          0.4390          0.2145        0.2605
4173    2   0.600     0.475  ...          0.5255          0.2875        0.3080
4174    0   0.625     0.485  ...          0.5310          0.2610        0.2960
4175    2   0.710     0.555  ...          0.9455          0.3765        0.4950

[4176 rows x 8 columns]

In [212]:
y=datasets[['Rings']]
y

Rings
0         7
1         9
2        10
3         7
4         8
...     ...
4171     11
4172     10
4173      9
4174     10
4175     12

[4176 rows x 1 columns]

In [213]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=90)


In [361]:
scaler = MinMaxScaler() 
scaler.fit(x_train) 
 
scaled_xtrain_data = scaler.transform(x_train) 
scaler_xtest_data = scaler.transform(x_test) 
scaled_xtrain_data

array([[0.        , 0.80405405, 0.76470588, ..., 0.41444444, 0.40026333,
        0.3552566 ],
       [1.        , 0.7027027 , 0.69747899, ..., 0.26518519, 0.2764977 ,
        0.24265072],
       [1.        , 0.74324324, 0.74789916, ..., 0.43444444, 0.28703094,
        0.36721475],
       ...,
       [1.        , 0.69594595, 0.69747899, ..., 0.44259259, 0.29822251,
        0.30742402],
       [0.5       , 0.37837838, 0.33613445, ..., 0.05703704, 0.06583278,
        0.05630294],
       [0.        , 0.56081081, 0.52941176, ..., 0.12592593, 0.15404872,
        0.18285999]])

In [362]:
scaler_xtest_data

array([[1.        , 0.67567568, 0.67226891, ..., 0.40851852, 0.31928901,
        0.29247633],
       [1.        , 0.57432432, 0.56302521, ..., 0.26666667, 0.20671494,
        0.23617339],
       [0.        , 0.50675676, 0.5210084 , ..., 0.23481481, 0.15865701,
        0.1305431 ],
       ...,
       [1.        , 0.37162162, 0.35294118, ..., 0.07296296, 0.06319947,
        0.06826109],
       [0.5       , 0.45945946, 0.42857143, ..., 0.12296296, 0.10862409,
        0.0896861 ],
       [1.        , 0.62162162, 0.61344538, ..., 0.26222222, 0.24884793,
        0.17737917]])

In [363]:
scaler = MinMaxScaler() 
scaler.fit(y_train) 
 
scaled_ytrain_data = scaler.transform(y_train) 
scaler_ytest_data = scaler.transform(y_test) 
scaled_ytrain_data

array([[0.35714286],
       [0.39285714],
       [0.57142857],
       ...,
       [0.28571429],
       [0.21428571],
       [0.35714286]])

In [364]:
scaler_ytest_data

array([[0.42857143],
       [0.28571429],
       [0.25      ],
       [0.25      ],
       [0.35714286],
       [0.21428571],
       [0.28571429],
       [0.39285714],
       [0.32142857],
       [0.17857143],
       [0.10714286],
       [0.35714286],
       [0.46428571],
       [0.35714286],
       [0.28571429],
       [0.28571429],
       [0.32142857],
       [0.10714286],
       [0.21428571],
       [0.35714286],
       [0.21428571],
       [0.39285714],
       [0.25      ],
       [0.21428571],
       [0.28571429],
       [0.28571429],
       [0.32142857],
       [0.32142857],
       [0.46428571],
       [0.17857143],
       [0.35714286],
       [0.39285714],
       [0.28571429],
       [0.28571429],
       [0.46428571],
       [0.42857143],
       [0.32142857],
       [0.32142857],
       [0.32142857],
       [0.32142857],
       [0.25      ],
       [0.28571429],
       [0.25      ],
       [0.39285714],
       [0.32142857],
       [0.53571429],
       [0.5       ],
       [0.321

In [365]:
from keras.layers import Dense, Activation
from keras.optimizers import RMSprop
from keras.utils import np_utils

In [369]:
from keras.models import Sequential
model = Sequential()
model.add(Dense(32, input_dim=8))
model.add(Activation('relu'))
model.add(Dense(32, input_dim=8))
model.add(Activation('relu'))
model.add(Dense(32, input_dim=8))
model.add(Activation('relu'))

model.add(Dense(1))
model.add(Activation('relu'))

In [377]:
rmsprop = RMSprop(lr=0.001)
model.compile(optimizer=rmsprop, loss='mse', metrics=['mae'])

In [378]:
model.fit(scaled_xtrain_data,scaled_ytrain_data , batch_size=32, epochs=10)

Epoch 1/10
105/105 [==============================] - 1s 1ms/step - loss: 0.0057 - mae: 0.0537
Epoch 2/10
105/105 [==============================] - 0s 1ms/step - loss: 0.0055 - mae: 0.0525
Epoch 3/10
105/105 [==============================] - 0s 1ms/step - loss: 0.0055 - mae: 0.0521
Epoch 4/10
105/105 [==============================] - 0s 1ms/step - loss: 0.0055 - mae: 0.0527
Epoch 5/10
105/105 [==============================] - 0s 1ms/step - loss: 0.0058 - mae: 0.0538
Epoch 6/10
105/105 [==============================] - 0s 2ms/step - loss: 0.0055 - mae: 0.0531
Epoch 7/10
105/105 [==============================] - 0s 1ms/step - loss: 0.0059 - mae: 0.0535
Epoch 8/10
105/105 [==============================] - 0s 1ms/step - loss: 0.0054 - mae: 0.0526
Epoch 9/10
105/105 [==============================] - 0s 1ms/step - loss: 0.0056 - mae: 0.0529
Epoch 10/10
105/105 [==============================] - 0s 1ms/step - loss: 0.0055 - mae: 0.0529


In [379]:
pred = model.predict(scaler_xtest_data)

In [380]:
pred

array([[0.3046235 ],
       [0.29967535],
       [0.23398563],
       [0.28654838],
       [0.37126166],
       [0.28196195],
       [0.3098614 ],
       [0.3562799 ],
       [0.339758  ],
       [0.19001827],
       [0.08292703],
       [0.37416002],
       [0.35686284],
       [0.4624855 ],
       [0.3496679 ],
       [0.32469678],
       [0.34230554],
       [0.18914017],
       [0.17259488],
       [0.38158602],
       [0.23862374],
       [0.38104162],
       [0.28070694],
       [0.19472782],
       [0.3623765 ],
       [0.2732988 ],
       [0.38705796],
       [0.29231888],
       [0.3664477 ],
       [0.21598229],
       [0.34242013],
       [0.39541012],
       [0.26580757],
       [0.35808933],
       [0.35545516],
       [0.39746714],
       [0.33717805],
       [0.38283014],
       [0.32738203],
       [0.37903595],
       [0.32357502],
       [0.30255327],
       [0.25828183],
       [0.45514804],
       [0.35307795],
       [0.34856582],
       [0.32204768],
       [0.350

In [381]:
scaler_ytest_data

array([[0.42857143],
       [0.28571429],
       [0.25      ],
       [0.25      ],
       [0.35714286],
       [0.21428571],
       [0.28571429],
       [0.39285714],
       [0.32142857],
       [0.17857143],
       [0.10714286],
       [0.35714286],
       [0.46428571],
       [0.35714286],
       [0.28571429],
       [0.28571429],
       [0.32142857],
       [0.10714286],
       [0.21428571],
       [0.35714286],
       [0.21428571],
       [0.39285714],
       [0.25      ],
       [0.21428571],
       [0.28571429],
       [0.28571429],
       [0.32142857],
       [0.32142857],
       [0.46428571],
       [0.17857143],
       [0.35714286],
       [0.39285714],
       [0.28571429],
       [0.28571429],
       [0.46428571],
       [0.42857143],
       [0.32142857],
       [0.32142857],
       [0.32142857],
       [0.32142857],
       [0.25      ],
       [0.28571429],
       [0.25      ],
       [0.39285714],
       [0.32142857],
       [0.53571429],
       [0.5       ],
       [0.321

In [382]:
pred-scaler_ytest_data

array([[-1.23947914e-01],
       [ 1.39610597e-02],
       [-1.60143673e-02],
       [ 3.65483761e-02],
       [ 1.41187991e-02],
       [ 6.76762334e-02],
       [ 2.41471061e-02],
       [-3.65772332e-02],
       [ 1.83294373e-02],
       [ 1.14468379e-02],
       [-2.42158313e-02],
       [ 1.70171644e-02],
       [-1.07422871e-01],
       [ 1.05342635e-01],
       [ 6.39536210e-02],
       [ 3.89824935e-02],
       [ 2.08769696e-02],
       [ 8.19973137e-02],
       [-4.16908392e-02],
       [ 2.44431581e-02],
       [ 2.43380240e-02],
       [-1.18155267e-02],
       [ 3.07069421e-02],
       [-1.95578911e-02],
       [ 7.66622254e-02],
       [-1.24154857e-02],
       [ 6.56293886e-02],
       [-2.91096909e-02],
       [-9.78380271e-02],
       [ 3.74108596e-02],
       [-1.47227262e-02],
       [ 2.55297763e-03],
       [-1.99067167e-02],
       [ 7.23750421e-02],
       [-1.08830554e-01],
       [-3.11042922e-02],
       [ 1.57494800e-02],
       [ 6.14015715e-02],
       [ 5.9

In [383]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

In [384]:
from sklearn import metrics
import numpy as np

metrics.mean_squared_error(scaler_ytest_data, pred)
print('RMSE：',np.sqrt(metrics.mean_squared_error(scaler_ytest_data,pred)))

RMSE： 0.07452238255924311


In [385]:
print(mape(scaler_ytest_data,pred))

15.98532765533694


In [386]:
print('MAE:',metrics.mean_absolute_error(scaler_ytest_data, pred))

MAE: 0.05266923754668896
